export const COINGECKO_CONFIG = {
  BASE_URL: "https://api.coingecko.com/api/v3",
  ENDPOINTS: {
    MARKETS: "/coins/markets",
    SEARCH: "/search/trending",
    COIN_DETAILS: "/coins/{{id}}",
    SIMPLE_PRICE: "/simple/price",
  },
  PARAMS: {
    VS_CURRENCY: "usd",
    ORDER: "market_cap_desc",
    PER_PAGE: 30,
    PAGE: 1,
    SPARKLINE: false,
  },
  MARKET_CHART: (coinId: string, days: string | number, interval: string) =>
    `/coins/${coinId.toLowerCase()}/market_chart?vs_currency=usd&days=${days}&interval=${interval}`,
  SIMPLE_PRICE_URL: (assetIds: string) => 
    `${COINGECKO_CONFIG.BASE_URL}${COINGECKO_CONFIG.ENDPOINTS.SIMPLE_PRICE}?ids=${assetIds}&vs_currencies=usd&include_24hr_change=true`,
} as const;

export const CRYPTO_CONFIG = {
  MEMECOIN_IDS: ["shiba-inu", "pepe", "floki-inu", "bonk"],
  TOP_CRYPTO_COUNT: 10,
  CURRENCY: COINGECKO_CONFIG.PARAMS.VS_CURRENCY,
  ORDER_BY: COINGECKO_CONFIG.PARAMS.ORDER,
  CRYPTO_IDS: [
    "bitcoin",
    "ethereum",
    "binancecoin",
    "solana",
    "cardano",
    "tron",
    "sui",
    "monero",
    "pepe",
    "xrp",
    "trump",
    "uniswap",
    "cosmos",
    "worldcoin",
    "hyperliquid",
    "story",
  ],
} as const;

export const CRYPTO_ICONS: { [key: string]: string } = {
  // Main tracked cryptocurrencies
  BTC: "₿",
  ETH: "Ξ",
  BNB: "B",
  SOL: "◎",
  ADA: "₳",
  SHIB: "🐕",
  PEPE: "🐸",
  FLOKI: "🐺",
  USDT: "₮",

  // Common trending cryptocurrencies
  XRP: "✕",
  DOT: "●",
  LINK: "🔗",
  MATIC: "⬡",
  AVAX: "🅰",
  LTC: "Ł",
  XLM: "★",
  XMR: "ɱ",
  ATOM: "⚛️",
  UNI: "🦄",
  AAVE: "🦇",
  CAKE: "🥞",
  SUSHI: "🍣",
  YFI: "💰",
  COMP: "🏦",
  SNX: "⚡",
  MKR: "🏭",
  CRV: "🔄",
  "1INCH": "1️⃣",
  ALGO: "🔢",
  NEAR: "Ⓝ",
  FTM: "👻",
  GRT: "🌐",
  HBAR: "ⓗ",
  ICP: "🌐",
  MANA: "🎮",
  THETA: "θ",
  TRX: "T",
  VET: "Ⓥ",
  XTZ: "ꜩ",
  ZEC: "ⓩ",
} as const;
