import { API_CONFIG } from "./api";
import { CRYPTO_CONFIG } from "./crypto";

export const PRICE_SLIDER_CONFIG = {
  REFRESH_INTERVAL: 30000,
  MAX_RETRIES: 5,
  RETRY_DELAY: {
    BASE: 1000,
    MAX: 30000,
  },
  PRICE_FORMAT: {
    MIN_FRACTION_DIGITS: 2,
    MAX_FRACTION_DIGITS: {
      SMALL: 6,
      LARGE: 2,
    },
  },
  ANIMATION: {
    DURATION: 30,
  },
  API: {
    URL: `${API_CONFIG.COINGECKO.BASE_URL}${API_CONFIG.COINGECKO.ENDPOINTS.MARKETS}`,
    PARAMS: API_CONFIG.COINGECKO.PARAMS,
    CRYPTO_IDS: CRYPTO_CONFIG.CRYPTO_IDS,
  },
  DUPLICATION_FACTOR: 6,
} as const;
